# Generated by Django 4.1 on 2023-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='amount_of_products',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='passcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
