# Generated by Django 4.1 on 2023-01-13 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_store_owner_store_owner_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
