# Generated by Django 4.1 on 2023-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='passcode',
            field=models.CharField(max_length=1000),
        ),
    ]
