# Generated by Django 4.1 on 2023-01-18 14:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_store_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('owner_username', models.CharField(max_length=10000)),
                ('store_id', models.CharField(max_length=1000)),
                ('image_one', models.ImageField(upload_to='images/<django.db.models.fields.CharField>')),
                ('image_two', models.ImageField(upload_to='images/<django.db.models.fields.CharField>')),
                ('image_three', models.ImageField(upload_to='images/<django.db.models.fields.CharField>')),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('amount_of_orders', models.IntegerField(default=0)),
            ],
        ),
    ]
