# Generated by Django 4.1 on 2023-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_one',
            new_name='first_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_three',
            new_name='second_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_two',
            new_name='third_image',
        ),
    ]
