# Generated by Django 4.1 on 2023-01-26 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_image_one_product_first_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=10000)),
            ],
        ),
    ]
