# Generated by Django 4.1 on 2023-01-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user',
            new_name='user_username',
        ),
    ]
