# Generated by Django 4.1 on 2023-01-26 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_user_search_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=10000)),
                ('user_username', models.CharField(max_length=10000)),
            ],
        ),
    ]
