# Generated by Django 4.1 on 2023-01-31 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
