# Generated by Django 4.1 on 2023-02-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
