# Generated by Django 4.1 on 2023-02-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
