# Generated by Django 4.1 on 2023-02-01 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=10000)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=10000)),
                ('address_id', models.CharField(max_length=10000)),
                ('cart_detail_id', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
