# Generated by Django 4.1 on 2023-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store_id',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
    ]
