# Generated by Django 4.1 on 2023-03-04 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
