# Generated by Django 4.1.7 on 2023-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_wishlist_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
