# Generated by Django 4.1.7 on 2023-03-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='post_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
