# Generated by Django 4.1.7 on 2023-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_address_unique_shop_address_user_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_shop_address_user_username',
        ),
    ]
