# Generated by Django 4.1.7 on 2023-03-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_address_unique_shop_address_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
    ]
