# Generated by Django 4.1.7 on 2023-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_order_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
